// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AtomsBaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    AtomsBaseLogo: typeof import('./components/atoms/BaseLogo.vue')['default']
    AtomsSearchInput: typeof import('./components/atoms/SearchInput.vue')['default']
    AtomsXIcon: typeof import('./components/atoms/XIcon.vue')['default']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/atoms/BaseCheckbox.vue')['default']
    BaseLogo: typeof import('./components/atoms/BaseLogo.vue')['default']
    BaseText: typeof import('./components/atoms/BaseText.vue')['default']
    BaseTitle: typeof import('./components/atoms/BaseTitle.vue')['default']
    CheckboxList: typeof import('./components/molecules/CheckboxList.vue')['default']
    FacetTitle: typeof import('./components/atoms/FacetTitle.vue')['default']
    FacetValue: typeof import('./components/atoms/FacetValue.vue')['default']
    GithubIcon: typeof import('./components/atoms/GithubIcon.vue')['default']
    MoleculesSearchInput: typeof import('./components/molecules/SearchInput.vue')['default']
    OrganismsNavbar: typeof import('./components/organisms/Navbar.vue')['default']
    OrganismsTheNavbar: typeof import('./components/organisms/TheNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/molecules/SearchInput.vue')['default']
    TheNavbar: typeof import('./components/organisms/TheNavbar.vue')['default']
    TwitterIcon: typeof import('./components/atoms/TwitterIcon.vue')['default']
    XIcon: typeof import('./components/atoms/XIcon.vue')['default']
  }
}
