// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseCard: typeof import('./components/atoms/BaseCard.vue')['default']
    BaseCheckbox: typeof import('./components/atoms/BaseCheckbox.vue')['default']
    BaseLogo: typeof import('./components/atoms/BaseLogo.vue')['default']
    BaseSelect: typeof import('./components/molecules/BaseSelect.vue')['default']
    BaseText: typeof import('./components/atoms/BaseText.vue')['default']
    BaseTitle: typeof import('./components/atoms/BaseTitle.vue')['default']
    CheckboxList: typeof import('./components/molecules/CheckboxList.vue')['default']
    DropdownArrow: typeof import('./components/atoms/DropdownArrow.vue')['default']
    GithubIcon: typeof import('./components/atoms/GithubIcon.vue')['default']
    HalfSolidStarIcon: typeof import('./components/atoms/HalfSolidStarIcon.vue')['default']
    MeiliSearchInput: typeof import('./components/organisms/MeiliSearchInput.vue')['default']
    MeiliSearchResults: typeof import('./components/organisms/MeiliSearchResults.vue')['default']
    MeiliSearchStats: typeof import('./components/organisms/MeiliSearchStats.vue')['default']
    ProductCard: typeof import('./components/organisms/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/molecules/SearchInput.vue')['default']
    SelectArrow: typeof import('./components/atoms/SelectArrow.vue')['default']
    SolidStarIcon: typeof import('./components/atoms/SolidStarIcon.vue')['default']
    StarIcon: typeof import('./components/atoms/StarIcon.vue')['default']
    StarRating: typeof import('./components/molecules/StarRating.vue')['default']
    TheNavbar: typeof import('./components/organisms/TheNavbar.vue')['default']
    TwitterIcon: typeof import('./components/atoms/TwitterIcon.vue')['default']
    XIcon: typeof import('./components/atoms/XIcon.vue')['default']
  }
}
